query ($childId: ID!){
    child(childId: $childId) {
        histories {
            id
            name
            checkedAt
            room {
                id
                number
            }
            createdAt
        }
        events {
            event
            createdAt
        }
    }
}
